#!/bin/bash
#
# console_msg_prefix is "🪄 🤖 [magicmake]:" written in ANSI colors
# to make it visually easier to identify messages from magicmake
#
console_msg_prefix="🪄 🤖 [38;5;39mm[38;5;48ma[38;5;154mg[38;5;208mi[38;5;199mc[38;5;93mm[38;5;33ma[38;5;49mk[38;5;118me[0m:"
usage() {
  cat 1>&2 <<USAGE
$console_msg_prefix detect and install missing packages when building from source

Usage:
  [1mmagicmake[0m [[1m-yqhlc[0m] [build_command [build_arguments]]

Options:
  [1m-y[0m  assume "yes" as an answer to all prompts and run non-interactively
  [1m-q[0m  run quietly; suppress output from build and package install commands
  [1m-h[0m  show this help, then exit
  [1m-l[0m  show list of packages suggested
  [1m-c[0m  clear list of packages suggested

USAGE
  exit 1
}

prompt=1
quiet=0
while getopts yqhlc opt
do
  case "$opt" in
    y)
      prompt=0
      ;;
    q)
      quiet=1
      ;;
    h)
      usage
      ;;
    l)
      suggested_packages=$(psql -X -t -A -c "SELECT string_agg(package, ' ') FROM magicmake.suggested_packages")
      echo "$console_msg_prefix suggested packages: [37;1m$suggested_packages[0m"
      exit 0
      ;;
    c)
      psql -Xqc "TRUNCATE magicmake.suggested_packages" && \
      echo "$console_msg_prefix cleared list of suggested packages ✅"
      exit 0
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))

if [ -z "$MAGICMAKE_BUILD_CMD" ]
then
  if [ $# -eq 0 ]
  then
    MAGICMAKE_BUILD_CMD="make"
  else
    MAGICMAKE_BUILD_CMD="$@"
  fi
fi

if [ -z "$MAGICMAKE_INSTALL_CMD" ]
then
  if [ $prompt = 0 ]
  then
    MAGICMAKE_INSTALL_CMD="sudo apt-get -y install"
  else
    MAGICMAKE_INSTALL_CMD="sudo apt install"
  fi
fi

strace_log_dir=$(mktemp -d)
strace_log_file="$strace_log_dir/strace.log"

#
# allow read permissions to anyone on
# so that the PostgreSQL function can read it
#
chmod o+rx "$strace_log_dir"
#
# loop until there are no more packages to install
#
while true;
do
  #
  # the MAGICMAKE_BUILD_CMD is run via `strace` which will log the full path
  # of any successful/unsuccessful file accesses
  #
  if [ $quiet = 1 ]
  then
    strace -e trace=%file,%process -o $strace_log_file -ff $MAGICMAKE_BUILD_CMD &>/dev/null
  else
    strace -e trace=%file,%process -o $strace_log_file -ff $MAGICMAKE_BUILD_CMD
  fi
  chmod o+r "$strace_log_file".*
  #
  # since build tools look for files at different paths,
  # the same file_name might at first be missing at some path(s)
  # but then eventually be found at some other path
  #
  # to determine what file_names are truly missing,
  # the magicmake.suggest_packages() PostgreSQL function
  # will compute the set of file_names missing at path(s)
  # except the file_names that were found at some path(s)
  #
  # magicmake.suggest_packages() returns a list of packages to install
  # or no rows if no packages to install could be found
  #
  count=0
  installed_packages=""
  for package in $(psql -X -t -A -c "SELECT magicmake.suggest_packages('$strace_log_dir')")
  do
    count=$((count+1))
    install=0
    if [ $prompt = 0 ]
    then
      echo "$console_msg_prefix installing [37;1m$package[0m"
      install=1
    else
      read -p "$console_msg_prefix do you want to install [37;1m$package[0m? [Y/n] " -r yes_no
      if [[ "$yes_no" =~ ^[Yy]$ ]] || [[ -z "$yes_no" ]]
      then
        install=1
      else
        install=0
      fi
    fi
    if [ $install = 1 ]
    then
      #
      # cannot be quiet unless non-interactive since the build command´
      # might display prompts otherwise
      #
      if [ $quiet = 1 ] && [ $prompt = 0 ]
      then
        $MAGICMAKE_INSTALL_CMD $package &>/dev/null
      else
        $MAGICMAKE_INSTALL_CMD $package
      fi
      installed_packages+=" $package"
    fi
  done
  rm -f "$strace_log_file".*
  if [ $count = 0 ]
  then
    echo "$console_msg_prefix no more packages to install ✅"
    if [ ! -z "$installed_packages" ]
    then
      echo "installed: [37;1m$installed_packages[0m"
    fi
    break
  fi
done
#
# the temporary strace file is removed at the end
#
rm -rf "$strace_log_dir"
