#!/bin/bash
#
# 🪄🤖 magicmake - auto-install missing packages required when building from source
#
usage() { echo "Usage: $0 [-y] [-q] [build_command [build_arguments]]" 1>&2; exit 1; }

prompt=1
quiet=0
while getopts y:q opt
do
  case "$opt" in
    y)
      prompt=0
      ;;
    q)
      quiet=1
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))

if [ -z "$MAGICMAKE_BUILD_CMD" ]
then
  if [ $# -eq 0 ]
  then
    MAGICMAKE_BUILD_CMD="make"
  else
    MAGICMAKE_BUILD_CMD="$@"
  fi
fi

if [ -z "$MAGICMAKE_INSTALL_CMD" ]
then
  if [ $prompt = 0 ]
  then
    MAGICMAKE_INSTALL_CMD="sudo apt-get -y install"
  else
    MAGICMAKE_INSTALL_CMD="sudo apt install"
  fi
fi

strace_log_file=$(mktemp)
#
# allow read permissions to anyone on
# the strace_log_file so that the PostgreSQL
# function can read it
#
chmod o+r $strace_log_file
#
# show an ANSI colored "[magicmake]" console log line prefix
# to make it visually easier to identify messages from magicmake
#
LOG_PREFIX="🪄 🤖 [38;5;39mm[38;5;48ma[38;5;154mg[38;5;208mi[38;5;199mc[38;5;93mm[38;5;33ma[38;5;49mk[38;5;118me[0m:"
#
# loop until there are no more packages to install
#
while true;
do
  #
  # the MAGICMAKE_BUILD_CMD is run via `strace` which will log the full path
  # of any successful/unsuccessful file accesses
  #
  if [ $quiet = 1 ]
  then
    strace -e trace=%file,%process -o $strace_log_file -f $MAGICMAKE_BUILD_CMD &>/dev/null
  else
    strace -e trace=%file,%process -o $strace_log_file -f $MAGICMAKE_BUILD_CMD
  fi
  #
  # since build tools look for files at different paths,
  # the same file_name might at first be missing at some path(s)
  # but then eventually be found at some other path
  #
  # to determine what file_names are truly missing,
  # the magicmake.suggest_packages() PostgreSQL function
  # will compute the set of file_names missing at path(s)
  # except the file_names that were found at some path(s)
  #
  # magicmake.suggest_packages() returns a list of packages to install
  # or no rows if no packages to install could be found
  #
  count=0
  for package in $(psql -X -t -A -c "SELECT magicmake.suggest_packages('$strace_log_file')")
  do
    count=$((count+1))
    install=0
    if [ $prompt = 0 ]
    then
      echo "$LOG_PREFIX installing [37;1m$package[0m"
      install=1
    else
      read -p "$LOG_PREFIX do you want to install [37;1m$package[0m? [Y/n] " -r yes_no
      if [[ "$yes_no" =~ ^[Yy]$ ]] || [[ -z "$yes_no" ]]
      then
        install=1
      else
        install=0
      fi
    fi
    if [ $install = 1 ]
    then
      $MAGICMAKE_INSTALL_CMD $package
    fi
  done
  if [ $count = 0 ]
  then
    echo "$LOG_PREFIX no more packages to install ✅"
    break
  fi
done
#
# the temporary strace file is removed at the end
#
rm -f "$strace_log_file"
